kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: context-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: context-server
  minReplicas: 1
  maxReplicas: 1
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metric:
        name: avg_connected_clients
      # target 5000 connected clients per server
      target:
        type: Value
        averageValue: 5000

