kind: Service
apiVersion: v1
metadata:
  annotations:
    config.linkerd.io/opaque-ports: "8080"
  labels:
    app: context-server
  name: context-server
  namespace: kubernetes-dashboard
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 32298
    - name: http-prom
      port: 9900
      targetPort: http-prom
      nodePort: 32299
  selector:
    app: context-server
  type: NodePort
