---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluent-output
  namespace: metrics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azureblob-fuse-standard-grs
  volumeName: "fluent-bit-output"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluent-bit-output
spec:
  storageClassName: azureblob-fuse-standard-grs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    # Make sure this is globally unique or you may run into issues with volumes mounting / attaching
    volumeHandle: fluent-output
    volumeAttributes:
      storageAccount: composeclusterprod
      containerName: fluent-bit-output
