---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim-fluent
  namespace: metrics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: model-csi-gcs-sc
  volumeName: "model-csi-gcs-pv-fluent"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-csi-gcs-pv-fluent
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: model-csi-gcs-sc
  csi:
    driver: gcs.csi.ofek.dev
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluent-output
  namespace: metrics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: model-csi-gcs-sc
  volumeName: "fluent-bit-output"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluent-bit-output
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: model-csi-gcs-sc
  csi:
    driver: gcs.csi.ofek.dev
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: metrics
