kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: context-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: context-server
  minReplicas: 4
  maxReplicas: 9
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 150
      - type: Percent
        value: 10
        periodSeconds: 150
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metric:
        name: avg_connected_clients
      # target 5000 connected clients per server
      target:
        type: AverageValue
        averageValue: 5000
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 4Gi


