---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: context-server
  name: context-server
  namespace: context-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: context-server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: context-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - context-server
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: context-server
          image: us-docker.pkg.dev/compose-cluster/compose-ai-server/context-server:dev-ecd3180
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-prom
              containerPort: 9900
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 10
            httpGet:
              scheme: HTTP
              path: /readinessz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: DYNACONF_MODEL_SERVER_URL
              value: "model-server.model-server.svc.cluster.local:8001"
            - name: DYNACONF_NUM_RETURN_SEQUENCES_CIRCUIT_TIMEOUT_SECONDS
              value: "0.7"
            - name: DYNACONF_FLUENT_LOG_LOCATION
              value: "/fluent-bit-input-logs/fluent-bit-input-logs-context-{time}.log"
            - name: ENABLE_METRICS
              value: "true"
            - name: DYNACONF_LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - mountPath: /fluent-bit-input-logs
              name: fluentbitonlylogs
            - name: models
              mountPath: /models
            - name: cache
              mountPath: /.cache
          securityContext:
            runAsUser: 1002
            runAsGroup: 1002
      volumes:
        # The name of this volume must be fluentbitonlylogs for fluent bit to be able to find all the logs files
        - name: fluentbitonlylogs
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: models
          persistentVolumeClaim:
            claimName: model-pv-claim-context
      securityContext:
        fsGroup: 1002
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim-context
  namespace: context-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: model-csi-gcs-sc
  volumeName: "model-csi-gcs-pv-context"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-csi-gcs-pv-context
  annotations:
    pv.beta.kubernetes.io/gid: "1002"
  namespace: context-server
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: model-csi-gcs-sc
  csi:
    driver: gcs.csi.ofek.dev
    # Make sure this is globally unique or you may run into issues with volumes mounting / attaching
    volumeHandle: context-model-directory
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: context-server
    volumeAttributes:
      gid: "1002"
      uid: "1002"
      dirMode: "0775"
      fileMode: "0664"
      implicitDirs: "true"
---
