kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: model-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-server
  minReplicas: 25
  maxReplicas: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Pods
        value: 3
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 15
      selectPolicy: Max
  metrics:
  - type: Pods
    pods:
      metric:
        name: model_server_total_latency
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average total latency of around 150ms per request (metric is microseconds)
      target:
        type: AverageValue
        averageValue: 150000
  - type: Pods
    pods:
      metric:
        name: avg_time_queue_us
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average queue time as low as possible, but has to be reasonable, not 0 (metric is microseconds)
      target:
        type: AverageValue
        averageValue: 25000
