kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: model-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-server
  minReplicas: 15
  maxReplicas: 45
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 15
      selectPolicy: Max
  metrics:
  - type: Pods
    pods:
      metric:
        name: avg_time_queue_us
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average queue time of around 150ms (metric is microseconds)
      target:
        type: AverageValue
        averageValue: 150000
  - type: Pods
    pods:
      metric:
        name: model_server_requests
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average queue time of around 150ms (metric is microseconds)
      target:
        type: AverageValue
        averageValue: 3000
  - type: Pods
    pods:
      metric:
        name: model_server_total_latency
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average queue time of around 150ms (metric is microseconds)
      target:
        type: AverageValue
        averageValue: 550

