---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: model-server
  name: model-server
  namespace: model-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: model-server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: model-server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: compose
      containers:
        - name: model-server
          image: us-docker.pkg.dev/compose-cluster/compose-ai-server/compose-triton:release-0.0.9-dev-b4503fe-l4
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 2000m
              memory: 12G
            limits:
              nvidia.com/gpu: 1
          ports:
            - name: newhttp
              containerPort: 8000
              protocol: TCP
            - name: grcp
              containerPort: 8001
              protocol: TCP
            - name: newhttp-prom
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            failureThreshold: 4 # 4*20s = 1:20 for recovering from failure
            httpGet:
              scheme: HTTP
              path: /v2/health/live
              port: 8000
            initialDelaySeconds: 180
            timeoutSeconds: 2
            periodSeconds: 20
          readinessProbe:
            failureThreshold: 20 # 20*15s = 5 min startup time required
            httpGet:
              scheme: HTTP
              path: /v2/health/ready
              port: 8000
            initialDelaySeconds: 180
            periodSeconds: 15
            timeoutSeconds: 3
          env:
            - name: DYNACONF_PROCESS_COUNT
              value: "1"
            - name: DYNACONF_FLUENT_LOG_LOCATION
              value: "/fluent-bit-input-logs/fluent-bit-input-logs-model-{time}.log"
            - name: ENABLE_METRICS
              value: "true"
            - name: DYNACONF_LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - mountPath: /fluent-bit-input-logs
              name: fluentbitonlylogs
            - name: models
              mountPath: /models
              readOnly: false
            - name: cupy
              mountPath: /.cupy
              readOnly: false
            - mountPath: /dev/shm
              name: dshm
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
      volumes:
        # The name of this volume must be fluentbitonlylogs for fluent bit to be able to find all the logs files
        - name: fluentbitonlylogs
          emptyDir: {}
        - name: cupy
          emptyDir: {}
        - name: models
          persistentVolumeClaim:
            claimName: model-pv-claim
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
      securityContext:
        fsGroup: 1001
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: model-csi-gcs-sc
provisioner: gcs.csi.ofek.dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim
  namespace: model-server
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: model-csi-gcs-sc
  volumeName: "model-csi-gcs-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-csi-gcs-pv
  namespace: model-server
  annotations:
    pv.beta.kubernetes.io/gid: "1001"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: model-csi-gcs-sc
  csi:
    driver: gcs.csi.ofek.dev
    # Make sure this is globally unique or you may run into issues with volumes mounting / attaching
    volumeHandle: model-server-models
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: model-server
    volumeAttributes:
      gid: "1001"
      uid: "1001"
      dirMode: "0775"
      fileMode: "0664"
      implicitDirs: "true"
---
