apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/csi-driver
  - ../base/loki
  - ../base/flux
  - ../base/nvidia-dcgm
  - context-server
  - model-server
  - fluent-bit
