kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: model-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Pods
    pods:
      metric:
        name: avg_time_queue_us
        selector:
          matchLabels:
            model: fasttransformer_generate
      # target an average queue time below 200ms (metric is microseconds)
      target:
        type: Value
        averageValue: 200000

