kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: model-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metric:
        name: contextserver_workload_total_histogram_seconds_bucket
      # target a p50 below 0.8 seconds
      target:
        type: Value
        averageValue: 800m

