{
 "title": "Alerts Dashboard",
 "description": "Alerts",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Context server rps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(contextserver_message_received_autocomplete_total[5m]))"
    }
   ]
  },
  {
   "title": "Output From Fluent Bit Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[5m]))"
    },
    {}
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Up Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(up{container=\"loki\"})",
     "legendFormat": "Loki"
    },
    {
     "expr": "sum(up{container=\"context-server\"})",
     "legendFormat": "Context server"
    },
    {
     "expr": "sum(up{container=\"model-server\"})",
     "legendFormat": "Model Server"
    },
    {
     "expr": "increase(fluentbit_uptime[1m]) >= bool 1",
     "legendFormat": "Fluent Bit"
    }
   ]
  }
 ]
}