apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    rules:
    - seriesQuery: '{__name__="contextserver_message_dropped_total",namespace!="",pod!="",autoscaling="model-server"}'
      resources:
        overrides:
          autoscaling:
            resource: "namespace"
      name:
        matches: "contextserver_message_dropped_total"
        as: "contextserver_dropped_messages"
      metricsQuery: 'sum(rate(contextserver_message_dropped_total[1m])) / sum(rate(contextserver_message_received_autocomplete_total[1m]))'
    - seriesQuery: '{__name__="contextserver_connected_clients",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "contextserver_connected_clients"
        as: "avg_connected_clients"
      metricsQuery: 'contextserver_connected_clients{<<.LabelMatchers>>}'
    - seriesQuery: '{__name__="nv_inference_queue_duration_us",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "nv_inference_queue_duration_us"
        as: "avg_time_queue_us"
      metricsQuery: '((increase(nv_inference_queue_duration_us{<<.LabelMatchers>>,model="fasttransformer_generate"}[1m])) / (1 + (increase(nv_inference_request_success{<<.LabelMatchers>>,model="fasttransformer_generate"}[1m]))))'
    - seriesQuery: '{__name__="nv_inference_request_duration_us",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "nv_inference_request_duration_us"
        as: "model_server_total_latency"
      metricsQuery: '((increase(nv_inference_request_duration_us{<<.LabelMatchers>>,model="fasttransformer_generate"}[1m])) / (1 + (increase(nv_inference_request_success{<<.LabelMatchers>>,model="fasttransformer_generate"}[1m]))))'

