apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    rules:
    - seriesQuery: |
         histogram_quantile(0.5, contextserver_workload_total_histogram_seconds_bucket{namespace!="", pod!=""})
      # resources:
        # "overrides":
          # "kubernetes_namespace": {resource: "namespace"}
          # "kubernetes_pod_name": {resource: "pod"}
      "name":
        "matches": "^(.*)_total"
        "as": ""
      "metricsQuery": |
        histogram_quantile(0.5, rate(contextserver_workload_total_histogram_seconds_bucket{<<.LabelMatchers>>}[5m]))

