apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    rules:
    - seriesQuery: '{__name__="contextserver_workload_total_histogram_seconds_bucket",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "^(.*)_bucket"
        as: "${1}_p50"
      metricsQuery: 'histogram_quantile(0.5, rate(contextserver_workload_total_histogram_seconds_bucket{<<.LabelMatchers>>}[5m]))'
    - seriesQuery: '{__name__="contextserver_connected_clients",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "contextserver_connected_clients"
        as: "avg_connected_clients"
      metricsQuery: 'contextserver_connected_clients{<<.LabelMatchers>>}'
    - seriesQuery: '{__name__="nv_inference_queue_duration_us",namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "nv_inference_queue_duration_us"
        as: "avg_time_queue_us"
      metricsQuery: 'avg(delta(nv_inference_queue_duration_us{<<.LabelMatchers>>}[5m])/(1+delta(nv_inference_request_success{<<.LabelMatchers>>}[5m]))) by (<<.GroupBy>>)'



