apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |-
    rules:
    - seriesQuery: |
        contextserver_workload_total_histogram_seconds_bucket{namespace!="", pod!=""}
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: ""
      metricsQuery: |
        histogram_quantile(0.5, rate(<<.Series>>{<<.LabelMatchers>>}[5m]))

