---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: context-server
  name: context-server
  namespace: context-server
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: context-server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: context-server
    spec:
      containers:
        - name: context-server
          image: us-docker.pkg.dev/compose-cluster/compose-ai-server/context:release-be58775

          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-prom
              containerPort: 9900
              protocol: TCP
          livenessProbe:
            failureThreshold: 6
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 15
          readinessProbe:
            failureThreshold: 10
            httpGet:
              scheme: HTTP
              path: /readinessz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            runAsUser: 1002
            runAsGroup: 1002
          env:
            - name: DYNACONF_MODEL_SERVER_URL
              value: "http://model-server.model-server.svc.cluster.local:8080"
            - name: DYNACONF_NUM_RETURN_SEQUENCES_CIRCUIT_TIMEOUT_SECONDS
              value: "0.7"
            - name: DYNACONF_FLUENT_LOG_LOCATION
              value: "/models/fluent-bit-input-logs/fluent-bit-input-logs-{time}.log"
            - name: ENABLE_METRICS
              value: "true"
          volumeMounts:
            - name: models
              mountPath: /models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: model-pv-claim-context
      securityContext:
        fsGroup: 1002
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim-context
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: model-csi-gcs-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-csi-gcs-pv-context
  annotations:
    pv.beta.kubernetes.io/gid: "1002"
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: model-csi-gcs-sc
  csi:
    driver: gcs.csi.ofek.dev
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: context-server
    volumeAttributes:
      gid: "1002"
      uid: "1002"
      dirMode: "0775"
      fileMode: "0664"
      implicitDirs: "true"
---
