kind: Service
apiVersion: v1
metadata:
  labels:
    app: context-server
  name: context-server
  namespace: kubernetes-dashboard
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 32298
  selector:
    app: context-server
  type: NodePort
