kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: context-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: context-server
  minReplicas: 3
  maxReplicas: 3
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 2
        periodSeconds: 300
      - type: Percent
        value: 10
        periodSeconds: 300
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
  metrics:
  # use a "Pods" metric, which takes the average of the
  # given metric across all pods controlled by the autoscaling target
  - type: Pods
    pods:
      metric:
        name: avg_connected_clients
      # target 3000 connected clients per server
      target:
        type: AverageValue
        averageValue: 3000
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 4Gi
