kind: Service
apiVersion: v1
metadata:
  labels:
    app: context-server
  name: context-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 32398
    - name: http-prom
      port: 9900
      targetPort: http-prom
      nodePort: 32399
  selector:
    app: context-server
  type: NodePort
