---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
      version: 2.5.0
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # Original values:
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  values:
    # https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml
    loki:
      persistence:
        type: pvc
        enabled: true
        storageClassName: ssd
        accessModes:
          - ReadWriteOnce
        size: 1000Gi
        finalizers:
          - kubernetes.io/pvc-protection
      resources:
        requests:
          cpu: 200m
          memory: 1000Mi
        limits:
          cpu: 200m
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: system
    # https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
    promtail:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
      serviceMonitor:
        enabled: true
        labels:
          app.kubernetes.io/part-of: system
