---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: kubernetes
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP
