---
apiVersion: v1
kind: Namespace
metadata:
  name: autoscaling
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: predictive-horizontal-pod-autoscaler
  namespace: autoscaling
spec:
  interval: 24h
  chart:
    spec:
      chart: ./helm/predictive-horizontal-pod-autoscaler
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 24h
  # https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler/blob/v0.13.2/helm/values.yaml
