---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: predictive-horizontal-pod-autoscaler
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://github.com/jthomperoo/predictive-horizontal-pod-autoscaler
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: predictive-horizontal-pod-autoscaler
  namespace: autoscaling
spec:
  interval: 24h
  chart:
    spec:
      chart: ./releases/download/v0.13.2/predictive-horizontal-pod-autoscaler-v0.13.2.tgz
      sourceRef:
        kind: GitRepository
        name: predictive-horizontal-pod-autoscaler
      interval: 24h
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
