kind: Service
apiVersion: v1
metadata:
  labels:
    app: model-server
  name: model-server
  namespace: model-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app: model-server
  type: ClusterIP
