kind: Service
apiVersion: v1
metadata:
  labels:
    app: model-server
  name: model-server
  namespace: model-server
spec:
  ports:
    - protocol: TCP
      port: 8000
      name: http
      targetPort: 8000
    - protocol: TCP
      port: 8001
      name: grpc
      targetPort: 8001
    - protocol: TCP
      port: 8002
      name: metrics
      targetPort: 8002
  selector:
    app: model-server
  type: LoadBalancer
