---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pv-claim-fluent
  namespace: metrics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azureblob-fuse-standard-grs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluent-bit-output
spec:
  storageClassName: azureblob-fuse-standard-grs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    # Make sure this is globally unique or you may run into issues with volumes mounting / attaching
    volumeHandle: fluent-output
    volumeAttributes:
      storageAccount: composeclusterprod
      containerName: fluent-bit-output
    nodeStageSecretRef:
      name: azure-fluent-storage-secret
      namespace: metrics
