apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: posthog
  namespace: posthog
spec:
  # https://github.com/compose-ai/charts-clickhouse/blob/main/charts/posthog/values.yaml
  values:
    # -- Site url specifies the canonical URL root the site can be accessed using.
    # This is used to e.g. generate shareable links to Dashboards.
    siteUrl: "posthog.prod.cluster.compose.ai"

    web:
      env:
        # -- Set google oauth 2 key. Requires posthog ee license.
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          value:
        # -- Set google oauth 2 secret. Requires posthog ee license.
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          value:
        # -- Set google oauth 2 whitelisted domains users can log in from.
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_DOMAINS
          value: "compose.ai"
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    worker:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    plugins:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsAsync:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsIngestion:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsAnalyticsIngestion:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    recordingsIngestion:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    recordingsBlobIngestion:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsExports:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsJobs:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    pluginsScheduler:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    temporalPyWorker:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    postgresql:
      master:
        nodeSelector:
          cloud.google.com/gke-nodepool: posthog
        tolerations:
          - key: "posthog"
            operator: "Exists"
            effect: "NoSchedule"
      persistence:
        # -- Enable persistence using PVC.
        enabled: true
        # -- PVC Storage Request for PostgreSQL volume.
        size: 100Gi
    _pgbouncer:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    redis:
      master:
        nodeSelector:
          cloud.google.com/gke-nodepool: posthog
        tolerations:
          - key: "posthog"
            operator: "Exists"
            effect: "NoSchedule"
    kafka:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      persistence:
        # - Enable data persistence using PVC.
        enabled: true
        # -- PVC Storage Request for Kafka data volume.
        size: 200Gi
      logRetentionBytes: _150_000_000_000
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    zookeeper:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    clickhouse:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      persistence:
        # -- Enable data persistence using PVC.
        enabled: true

        # -- Persistent Volume size
        size: 500Gi
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    hooks:
      nodeSelector:
        cloud.google.com/gke-nodepool: posthog
      tolerations:
        - key: "posthog"
          operator: "Exists"
          effect: "NoSchedule"
    ingress:
      # -- Ingress handler type. Defaults to `nginx` if nginx is enabled and to `clb` on gcp.
      type: "posthog-nginx"
      hostname: "posthog.prod.cluster.compose.ai"
