apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/loki
  - ../base/flux
  - ../base/nvidia-dcgm
  - ../base/posthog
  - context-server
  - model-server
  - fluent-bit
patchesStrategicMerge:
  - posthog/merge-values.yaml
