apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  strategy: production
  #prometheus:
    #server-url: "http://prometheus-kube-prometheus-prometheus.metrics.svc.cluster.local:9090"
  #metricsStorage:
    #type: prometheus
  collector:
    maxReplicas: 9
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    #storage:
      #options:
        #memory:
          #max-traces: 100000
  #query:
    #base-path: /jaeger
  agent:
    volumeMounts:
    - name: agent-volume
      mountPath: /tmp/agent
      readOnly: true
    volumes:
      - name: agent-volume
        secret:
          secretName: agent-secret
    imagePullSecrets:
    - name: agent-imagePullSecret

